export const seedOpportunities = [
  {
    title: 'Comics Star Wars — coleção 1 ao 70',
    collection: 'Planeta DeAgostini — Comics Star Wars',
    category: 'HQ',
    platform: 'OLX',
    price: 2250,
    condition: 'Usado — confirmar lombadas e volumes',
    status: 'Avaliando',
    url: 'https://sp.olx.com.br/sao-paulo-e-regiao/livros-e-revistas/colecao-comics-star-wars-1-ao-70-planeta-de-agostini-completa-1507986383',
    notes: 'Melhor preço encontrado. Anúncio visto desde julho de 2026; alvo de negociação: R$ 1.900–2.100.',
  },
  {
    title: 'Comics Star Wars — 70 volumes lacrados',
    collection: 'Planeta DeAgostini — Comics Star Wars',
    category: 'HQ',
    platform: 'Mercado Livre',
    price: 2900,
    condition: 'Lacrado',
    status: 'Wishlist',
    url: 'https://lista.mercadolivre.com.br/colecao-completa-comics-star-wars-70-volumes-lacrados',
    notes: 'Plano B da coleção completa; anúncio indicava frete grátis.',
  },
  {
    title: 'Comics Star Wars — coleção completa',
    collection: 'Planeta DeAgostini — Comics Star Wars',
    category: 'HQ',
    platform: 'Shopee',
    price: 3170,
    condition: 'Excelente estado',
    status: 'Wishlist',
    url: 'https://shopee.com.br/Cole%C3%A7%C3%A3o-Comics-Star-Wars-70-Volumes-Completa-i.404161550.58251414537',
    notes: 'Sebo Museu do Livro, Jundiaí. Confirmar disponibilidade antes de comprar.',
  },
  {
    title: 'Coleção Star Wars — 37 volumes',
    collection: 'Panini — HQs canônicas',
    category: 'HQ',
    platform: 'Mercado Livre',
    price: 1400,
    condition: 'Usado',
    status: 'Avaliando',
    url: 'https://lista.mercadolivre.com.br/colecao-star-wars-panini-hqs',
    notes: 'Lote grande para ampliar rapidamente a coleção; conferir lista de títulos e duplicatas.',
  },
  {
    title: 'Coleção completa — 14 volumes',
    collection: 'Panini — HQs canônicas',
    category: 'HQ',
    platform: 'Mercado Livre',
    price: 500,
    condition: 'Usado',
    status: 'Avaliando',
    url: 'https://lista.mercadolivre.com.br/colecao-star-wars-panini-hqs',
    notes: 'Boa relação entre preço e quantidade; validar quais arcos estão incluídos.',
  },
  {
    title: 'Darth Vader — coleção com 4 volumes',
    collection: 'Panini — Darth Vader',
    category: 'HQ',
    platform: 'Mercado Livre',
    price: 150,
    condition: 'Usado',
    status: 'Wishlist',
    url: 'https://lista.mercadolivre.com.br/colecao-star-wars-panini-hqs',
    notes: 'Bloco temático com bom preço de referência.',
  },
];

export const statusOptions = ['Avaliando', 'Wishlist', 'Comprado', 'Descartado'];
export const categoryOptions = ['HQ', 'Disney Deluxe Figurine Set', 'Disney Play Set', 'Livro', 'Outro'];
